=== samply/common-mailing/src/main/resources/MailSending.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:jxb="http://java.sun.com/xml/ns/jaxb" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  attributeFormDefault="unqualified"
  elementFormDefault="qualified"
  targetNamespace="http://schema.samply.de/config/MailSending"
  version="1.0"
  xmlns="http://schema.samply.de/config/MailSending"
  jxb:version="2.1"
>

  <!-- (in trunk directory) compile to Java object on command line with:
      xjc -encoding utf-8 -d .\src\main\java  -npa .\src\main\resources\MailSending.xsd
  -->

  <xsd:annotation>
    <xsd:appinfo>
      <jxb:schemaBindings>
        <jxb:package name="de.samply.common.mailing"/>
      </jxb:schemaBindings>
    </xsd:appinfo>
  </xsd:annotation>

  <xsd:complexType name="mailSending">
    <xsd:all>
      <xsd:element minOccurs="1" name="host" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>DNS name or IP address of mail server
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>

      <xsd:element name="protocol">
        <xsd:annotation>
          <xsd:documentation>Protocol to use for mail sending
          </xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="smtp"/>
            <xsd:enumeration value="smtps"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>

      <xsd:element name="port" type="xsd:int">
        <xsd:annotation>
          <xsd:documentation>Port name for mail server and protocol
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>

      <xsd:element minOccurs="1" name="fromAddress" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>Address that is set as default sender
            address of an email
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>

      <xsd:element minOccurs="0" name="fromName" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>Optional display name of the sender.
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>

      <xsd:element minOccurs="0" name="user" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>User name to login into mail server
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>

      <xsd:element minOccurs="0" name="password" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>Password for user to login into mail server
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>

      <xsd:element minOccurs="1" name="templateFolder" type="xsd:string">
        <xsd:annotation>
          <xsd:documentation>The folder contains the Mail templates.
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>

    </xsd:all>
  </xsd:complexType>

  <xsd:element name="mailSending" type="mailSending">
  </xsd:element>

</xsd:schema>

=== samply/common-mailing/src/test/resources/mailSending.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns1:mailSending
  xmlns:ns1="http://schema.samply.de/config/MailSending"
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:schemaLocation="http://schema.samply.de/config/MailSending http://schema.samply.de/config/MailSending.xsd">
  <ns1:fromAddress>noreply@samply.de</ns1:fromAddress>
  <ns1:fromName>Samply Mail</ns1:fromName>
  <ns1:host>mail.imbei.uni-mainz.de</ns1:host>
  <ns1:password></ns1:password>
  <ns1:port>25</ns1:port>
  <ns1:protocol>smtp</ns1:protocol>
  <ns1:templateFolder>./src/test/resources/exampleTemplates/</ns1:templateFolder>
  <ns1:user></ns1:user>
</ns1:mailSending>
